main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('receipts/', views.receipts_index, name='index'),
  path('receipts/<int:receipt_id>/', views.receipts_detail, name='detail'),
  path('receipts/create/', views.ReceiptCreate.as_view(), name='receipt_create'),
  path('receipts/<int:pk>/update/', views.ReceiptUpdate.as_view(), name='receipt_update'),
  path('receipts/<int:pk>/delete/', views.ReceiptDelete.as_view(), name='receipt_delete'),
  path('receipts/<int:receipt_id>/add_expense/', views.add_expense, name='add_expense'),
  path('receipt/<int:receipt_id>/assoc_people/<int:people_id>/', views.assoc_people, name='assoc_people'),
  path('receipt/<int:receipt_id>/unassoc_people/<int:people_id>/', views.unassoc_people, name='unassoc_people'),
  path('people/', views.PeopleList.as_view(), name='people_index'),
  path('people/<int:pk>/', views.PersonDetail.as_view(), name='people_detail'),
  path('people/create/', views.PersonCreate.as_view(), name='people_create'),
  path('people/<int:pk>/update', views.PersonUpdate.as_view(), name='people_update'),
  path('people/<int:pk>/delete', views.PersonDelete.as_view(), name='people_delete'),

]

receiptcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse

PAID = (
  ('P', 'Paid'),
  ('N', 'Not Paid Yet')
)

class People(models.Model):
  name = models.CharField(max_length=100)

  def __str__(self):
    return self.name
  
  
  def get_absolute_url(self):
    return reverse('people_detail', kwargs={'pk': self.id})

# Create your models here.
class Receipt(models.Model):
  name = models.CharField(max_length=100, null=True)
  restaurant = models.CharField(max_length=100)
  datepick = models.DateField(auto_now=False)
  total = models.DecimalField(max_digits=6, decimal_places=2)
  people = models.ManyToManyField(People)

  def __str__(self):
    return f'{self.name} ({self.id})'
  
  def get_absolute_url(self):
    return reverse('detail', kwargs={'receipt_id': self.id})

class Expense(models.Model):
  paid = models.CharField(
    max_length=1,
    choices=PAID,
    default=[1][0]
  )
  date = models.DateField('Date')

  receipt = models.ForeignKey(
    Receipt, on_delete=models.CASCADE
  )

  def __str__(self):
    return f"{self.get_paid_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Expense

class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['date', 'paid']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Receipt, People
from .forms import ExpenseForm


# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def receipts_index(request):
  receipts = Receipt.objects.all()
  return render (request, 'receipts/index.html', {
    'receipts': receipts
  })

def receipts_detail(request, receipt_id):
  receipt = Receipt.objects.get(id=receipt_id)
  id_list = receipt.people.all().values_list('id')
  people_receipt_doesnt_have = People.objects.exclude(id__in=id_list)
  expense_form = ExpenseForm
  return render(request, 'receipts/detail.html', {
    'receipt': receipt, 'expense_form': expense_form, 
    'people': people_receipt_doesnt_have
  })

class ReceiptCreate(CreateView):
  model = Receipt
  fields = '__all__'

class ReceiptUpdate(UpdateView):
  model = Receipt
  fields = ['restaurant', 'date', 'total']

class ReceiptDelete(DeleteView):
  model = Receipt
  success_url = '/receipts'

def add_expense(request, receipt_id):
  form = ExpenseForm(request.POST)
  if form.is_valid():
    new_expense = form.save(commit=False)
    new_expense.receipt_id = receipt_id
    new_expense.save()
    return redirect('detail', receipt_id=receipt_id)
  
class PeopleList(ListView):
  model = People

class PersonDetail(DetailView):
  model = People

class PersonCreate(CreateView):
  model = People
  fields = '__all__'

class PersonUpdate(UpdateView):
  model = People
  fields = ['name']

class PersonDelete(DeleteView):
  model = People
  success_url = '/people'

def assoc_people(request, receipt_id, people_id):
  Receipt.objects.get(id=receipt_id).people.add(people_id)
  return redirect('detail', receipt_id=receipt_id)

def unassoc_people(request, receipt_id, people_id):
  Receipt.objects.get(id=receipt_id).people.remove(people_id)
  return redirect('detail', receipt_id=receipt_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>About the Receipts Collector</h1>
  <hr />
  <footer>All Rights Reserved, &copy; 2023 Receipts Collector</footer>  
{% endblock %}
  

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Receipts Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper grey">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Receipts Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'people_create' %}">Add a Person</a></li>
          <li><a href="{% url 'people_index' %}">View All People</a></li>
          <li><a href="{% url 'receipt_create' %}">Add New Transaction</a></li>
          <li> <a href="{% url 'index' %}">View All Receipts</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer grey">
    <div class="right">All Rights Reserved, &copy; 2023 Receipts Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>HOME</h1>
{% endblock  %}

main_app/templates/main_app/people_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Person</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' people.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/people_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ people.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'people_update' people.id %}">Edit</a>
        <a href="{% url 'people_delete' people.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/people_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Person</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/people_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for person in people_list %}
  <a href="{% url 'people_detail' person.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ person.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/receipt_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Receipt?</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="yes" class="btn">
  <a href="{% url 'detail' receipt.id %}">Cancel</a>
</form>
{% endblock content %}

main_app/templates/main_app/receipt_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Transaction</h1>
{% endif %}


<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
  
  <script>
  const dateEl = document.getElementById('id_datepick');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  </script>
</form>

{% endblock %}

main_app/templates/receipts/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Receipt Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ receipt.name }}</span>
        <p>Restaurant: {{ receipt.restaurant|linebreaks }}</p>
        <p>Date: {{ receipt.datepick|linebreaks }}</p>
        <p>Total: {{ receipt.total|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'receipt_update' receipt.id %}">Edit</a>
        <a href="{% url 'receipt_delete' receipt.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_expense' receipt.id %}" method="POST">
    {% csrf_token %}
    <!-- Render the inputs -->
    {{ expense_form.as_p }}
    <input type="submit" class="btn" value="Update">
  </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Status</th></tr>
      </thead>
      <tbody>
        {% for expense in receipt.expense_set.all %}
        <tr>
          <td>{{expense.date}}</td>
          <td>{{expense.get_paid_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>Who Owes for {{ receipt.name }}</h3>
    {% if receipt.people.count %}
      {% for person in receipt.people.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">{{ person.name }}</span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_people' receipt.id person.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No People</h5>
    {% endif %}
  </div>
  <!-- Available People will come after this line -->
  <div class="col s6">
    <h3>Available People</h3>
    {% if people.count %}
      {% for person in people.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">{{ person.name }}</span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_people' receipt.id person.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{receipt.name}} Already Has All People Available</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
M.Datepicker.init(dateEl, {
  format: 'yyyy-mm-dd',
  defaultDate: new Date(),
  setDefaultDate: true,
  autoClose: true
});

  const selectEl = document.getElementById('id_paid');
  M.FormSelect.init(selectEl);

</script>
{% endblock %}

main_app/templates/receipts/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Receipts</h1>

{% for receipt in receipts %}
<a href="{% url 'detail' receipt.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ receipt.name }}</span>
      <p>Restaurant: {{ receipt.restaurant }}</p>
      <p>Date: {{ receipt.date }}</p>
      <p>Total: {{ receipt.total }}</p>
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}